# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/acomet/Documents/Learn2Slither

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/acomet/Documents/Learn2Slither

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acomet/Documents/Learn2Slither/CMakeFiles /home/acomet/Documents/Learn2Slither//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acomet/Documents/Learn2Slither/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /home/acomet/Documents/Learn2Slither/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Learn2Slither

# Build rule for target.
Learn2Slither: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Learn2Slither
.PHONY : Learn2Slither

# fast build rule for target.
Learn2Slither/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/build
.PHONY : Learn2Slither/fast

#=============================================================================
# Target rules for targets named SDL3-shared

# Build rule for target.
SDL3-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-shared
.PHONY : SDL3-shared

# fast build rule for target.
SDL3-shared/fast:
	$(MAKE) $(MAKESILENT) -f SDL/CMakeFiles/SDL3-shared.dir/build.make SDL/CMakeFiles/SDL3-shared.dir/build
.PHONY : SDL3-shared/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f SDL/CMakeFiles/SDL3_test.dir/build.make SDL/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named SDL_uclibc

# Build rule for target.
SDL_uclibc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL_uclibc
.PHONY : SDL_uclibc

# fast build rule for target.
SDL_uclibc/fast:
	$(MAKE) $(MAKESILENT) -f SDL/CMakeFiles/SDL_uclibc.dir/build.make SDL/CMakeFiles/SDL_uclibc.dir/build
.PHONY : SDL_uclibc/fast

Agent.o: Agent.cpp.o
.PHONY : Agent.o

# target to build an object file
Agent.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Agent.cpp.o
.PHONY : Agent.cpp.o

Agent.i: Agent.cpp.i
.PHONY : Agent.i

# target to preprocess a source file
Agent.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Agent.cpp.i
.PHONY : Agent.cpp.i

Agent.s: Agent.cpp.s
.PHONY : Agent.s

# target to generate assembly for a file
Agent.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Agent.cpp.s
.PHONY : Agent.cpp.s

Board.o: Board.cpp.o
.PHONY : Board.o

# target to build an object file
Board.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Board.cpp.o
.PHONY : Board.cpp.o

Board.i: Board.cpp.i
.PHONY : Board.i

# target to preprocess a source file
Board.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Board.cpp.i
.PHONY : Board.cpp.i

Board.s: Board.cpp.s
.PHONY : Board.s

# target to generate assembly for a file
Board.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Board.cpp.s
.PHONY : Board.cpp.s

SimpleStateStrategy.o: SimpleStateStrategy.cpp.o
.PHONY : SimpleStateStrategy.o

# target to build an object file
SimpleStateStrategy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/SimpleStateStrategy.cpp.o
.PHONY : SimpleStateStrategy.cpp.o

SimpleStateStrategy.i: SimpleStateStrategy.cpp.i
.PHONY : SimpleStateStrategy.i

# target to preprocess a source file
SimpleStateStrategy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/SimpleStateStrategy.cpp.i
.PHONY : SimpleStateStrategy.cpp.i

SimpleStateStrategy.s: SimpleStateStrategy.cpp.s
.PHONY : SimpleStateStrategy.s

# target to generate assembly for a file
SimpleStateStrategy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/SimpleStateStrategy.cpp.s
.PHONY : SimpleStateStrategy.cpp.s

Snake.o: Snake.cpp.o
.PHONY : Snake.o

# target to build an object file
Snake.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Snake.cpp.o
.PHONY : Snake.cpp.o

Snake.i: Snake.cpp.i
.PHONY : Snake.i

# target to preprocess a source file
Snake.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Snake.cpp.i
.PHONY : Snake.cpp.i

Snake.s: Snake.cpp.s
.PHONY : Snake.s

# target to generate assembly for a file
Snake.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/Snake.cpp.s
.PHONY : Snake.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/main.cpp.s
.PHONY : main.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/utils.cpp.s
.PHONY : utils.cpp.s

visuals.o: visuals.cpp.o
.PHONY : visuals.o

# target to build an object file
visuals.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/visuals.cpp.o
.PHONY : visuals.cpp.o

visuals.i: visuals.cpp.i
.PHONY : visuals.i

# target to preprocess a source file
visuals.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/visuals.cpp.i
.PHONY : visuals.cpp.i

visuals.s: visuals.cpp.s
.PHONY : visuals.s

# target to generate assembly for a file
visuals.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Learn2Slither.dir/build.make CMakeFiles/Learn2Slither.dir/visuals.cpp.s
.PHONY : visuals.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Learn2Slither"
	@echo "... SDL3-shared"
	@echo "... SDL3_test"
	@echo "... SDL_uclibc"
	@echo "... Agent.o"
	@echo "... Agent.i"
	@echo "... Agent.s"
	@echo "... Board.o"
	@echo "... Board.i"
	@echo "... Board.s"
	@echo "... SimpleStateStrategy.o"
	@echo "... SimpleStateStrategy.i"
	@echo "... SimpleStateStrategy.s"
	@echo "... Snake.o"
	@echo "... Snake.i"
	@echo "... Snake.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
	@echo "... visuals.o"
	@echo "... visuals.i"
	@echo "... visuals.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /home/acomet/Documents/Learn2Slither/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

